User/ksuvorin/development 224
damirzhamalatdinov/Velvet pull request #12
Opened 2023-05-01 15:03 UTC by SkippiDow

2023-05-01 15:07 UTC, Kvenecusghost commented
1. Перепутаны RXTX в GSM
2. Перепутаны RXTX в RFID
3. Может цепи светодиодов называть DOx, а не DIx?

2023-05-01 15:08 UTC, Kvenecusghost requested changes
Нужны поправки в схему

2023-05-01 16:39 UTC, Kvenecusghost commented
Добавить тестовые пады на все цифровые провода.
Добавить логотип КазАТУ на печатной плате
Разместить рядом с логотипом название и версию: Velvet Controller v2.0
Разместить поле для шести-символьного серийного номера: S/N: XX-XX-XX. Вместо XX необходимо разместить белые прямоугольник для нанесения серийного номера маркером

2023-05-03 15:40 UTC, Kvenecusghost commented
Думаю между DVDD и AVDD микросхемы DA1a не помешает ферритовая бусина, чтобы отфильтровать высокочастотные помехи от цифровых сигналов.

2023-05-10 08:02 UTC, SkippiDow commented
проверяй

2023-05-11 11:33 UTC, SkippiDow commented
Добавил пояснительные надписи на УГО STM32. Добавил спецификацию к микроконтроллеру

2023-05-12 15:35 UTC, Kvenecusghost approved these changes
Принято

2023-05-12 15:38 UTC, merged