DEVELOPMENT-205: Считывание данных с RFID
damirzhamalatdinov/Velvet pull request #17
Opened 2023-05-02 17:41 UTC by mrkamalov

https://tracker.yandex.ru/DEVELOPMENT-205
Считывание данных с RFID

2023-05-03 16:07 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/adc.c
> +  {
Неверная табуляция
```suggestion
    for(;;)
    {
```

2023-05-03 16:16 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Inc/rfid.h
> +extern uint8_t currentTag[6];
Использовать глобальные переменные довольно небезопасная практика. Предлагаю создать статичную структуру внутри rfid.c, которая будет содержать необходимые тебе переменные и создать внешний интерфейс с set/get функциями.

2023-05-04 03:19 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +void sendMsgToESP(void *argument){
Давай названия данных функций будем заканчивать на _worker. Это обычная практика для тредов

2023-05-04 03:26 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +	}
1) Для задач подобного рода больше подходит шаблон обработчика message queue. Создаётся очередь. Данный воркер должен ждать сообщения в очереди. Для отправки в очередь комманд создаётся внешний интерфейс, который отвечает за формирование и выталкивание сообщений в очередь. Плюс в том, что нет необходимости беспокоиться о мьютексах и прочем. Очередь гораздо более безопасна в плане реализации и последующей поддержки.
2) В чем необходимость использовать Transmit_IT? Мне кажется блокирующей отправки с ожиданием данных в DMA было бы достаточно.

2023-05-04 03:36 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/main.c
> +__weak void readWeight(void *argument)
```suggestion
__weak void readWeight_worker(void *argument)
```

2023-05-04 03:37 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/main.c
> +__weak void sendMsgToESP(void *argument)
```suggestion
__weak void sendMsgToESP_worker(void *argument)
```

2023-05-04 03:41 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +uint8_t currentTag[6] = {0};
Нужно обозначить эти переменные как static

2023-05-04 03:45 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +}
По моему нет необходимости в этом треде, так как запись и считывание в RFID все равно происходит последовательно, поэтому можно использовать тред readRfid.

2023-05-04 03:45 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +void readRfid(void *argument)
Предлагаю переименовать в 
```suggestion
void rfid_worker(void *argument)
```

2023-05-04 03:49 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Inc/app.h
> +void checkTasksTimeout(void);
Кажется эта функция не выполняется

2023-05-04 15:46 UTC, mrkamalov commented on Software/VelvetApp/Core/Inc/rfid.h
> +extern uint8_t currentTag[6];
Предлагаешь принимать по 1 байту и записывать их с помощью сеттера?

2023-05-04 15:48 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +void sendMsgToESP(void *argument){
честно говоря ни разу такого не видел. видел бывает Task добавляют

2023-05-04 16:13 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +	}
п.1 согласен. п.2 не понял ты предлагаешь блокирующий Transmit и Receive_DMA?

2023-05-04 16:14 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +uint8_t currentTag[6] = {0};
здесь согласен

2023-05-04 16:16 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Inc/rfid.h
> +extern uint8_t currentTag[6];
Совсем не обязательно. Геттеры и сеттеры могут принимать указатели на буферы. 
В целом не понятно зачем внешним интерфейсам знать что у тебя там в output/input буферах.
И внутреннее состояние RFID вроде бы тоже никому не нужно.
Надо подумать над модульностью кода. А то у тебя получается все модули между собой неразрывно связаны. Это не самый лучший вариант архитектуры. Нужно постараться сделать модули максимально независимыми. 
Это не касается этого участка, но в общем хочу заметить использовать глобальные семафоры и мьютексы тоже не есть гуд. Такой код довольно быстро превращается в неподдерживаемого монстра, потому что один только автор знает, что и зачем там дёргается. Поэтому эти средства нужно тоже максимально локализовывать. Для дёргания извне опять же можно написать внешний интерфейс.

2023-05-04 16:21 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +}
не совсем понял, что имеешь ввиду. разве что можно добавить очередь в readRfid и ожидать ответа. но при этом нам всё равно надо периодически сканировать метки, ведь их может и не быть в поле действия

2023-05-04 16:21 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +	}
Ага. Думаю это оправданно. Т.к. у тебя итак отдельный тред, трансмит фактически ничего не заблочит.

2023-05-04 16:22 UTC, mrkamalov commented on Software/VelvetApp/Core/Inc/app.h
> +void checkTasksTimeout(void);
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  /* USER CODE BEGIN Callback 0 */

  /* USER CODE END Callback 0 */
  if (htim->Instance == TIM1) {
    HAL_IncTick();
  }
  /* USER CODE BEGIN Callback 1 */
	if (htim->Instance == TIM6) {
		checkTasksTimeout();    
  }

2023-05-04 16:30 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +}
У тебя явно прослеживается такой алгоритм:
1. Инициализировать RFID
2. Считать информацию о считывателе (getReaderInfoCMD)
3. Если не считалось, ребутнуться
4. Войти в бесконечный цикл
5. Отправить команду считывания инвентарного номера
6. Получить ответ от модуля, если появилась метка в зоне действия

Как мне кажется этот алгоритм можно реализовать в рамках одного треда. Или обязательно это делать асинхронно?

2023-05-04 16:31 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +void sendMsgToESP(void *argument){
Можно и так. Главное обозначить, что это основная функция которую гоняет планировщик в треде

2023-05-04 16:35 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Inc/app.h
> +void checkTasksTimeout(void);
Упс, пропустил

2023-05-04 16:36 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +}
здесь можно конечно использовать очередь с таймаутом (например 1000 мс), чтобы если ничего не пришло, то он по новой запустил опрос

2023-05-04 16:42 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +}
Мне кажется можно просто прием с прерыванием использовать или даже poll с таймаутом в секунду.

2023-05-04 16:43 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +}
В идеале DMA если есть свободный канал

2023-05-12 16:35 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Inc/adc.h
> +
Считывание веса отдельная задача. Убери из этого PR плиз

2023-05-17 11:06 UTC, Kvenecusghost requested changes
Оставил замечания

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/app.c
> +extern osMessageQueueId_t espSendQueueHandle;
давай не будем использовать extern для очереди. Очередь можно просто задекларировать в esp.h. Ты же итак везде, где обращаешь к очереди подключаешь esp.h. extern можно использовать только в совсем крайних случаях.

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +#define ReceiveOK 1
Это можно объявить как typedef enum. Более безопасная декларация таких констант. Для команд отдельный enum и для возвращаемых значений отдельный enum

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/uartCallback.c
> +extern osMessageQueueId_t rfidReceiveQueueHandle;
То же самое замечание касательно extern

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +}
Нельз заменить просто memcpy?

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +uint8_t isTagsEqual(uint8_t* newTag, uint8_t* currentTag){
Нельзя ли заменить на memcmp?

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +extern UART_HandleTypeDef huart4;
Так хардкодить лучше не стоит. Лучше здесь объявить статичный указатель UART_HandleTypeDef * uart. Локально в этом файле использовать этот указатель. 
Добавить внешний интерфейс для передачи в этот указатель адреса нужного huartx. Этот внешний интерфейс дёргать при инициализации либы. 
Это защитит от ошибок в будущем, если захочется перестроиться на другой интерфейс. Достаточно будет просто изменить передаваемый указатель в одном месте.

У тебя еще где-то в паре мест реализовано через extern. Тоже нужно поправить.

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +	for(i=1;i<7;i++) sendBuffer[i] = tagBuf[i-1];
Можно заменить на memcpy

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +
Можно заменить на memcmp

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +		HAL_UART_Receive_DMA(&huart4,receiveBuffer,8);
1. Думаю, когда прием прекращается по таймауту нужно разряжать DMA и очищать буфер. Иначе состояние получается неоднозначное.
2. Обычно сначала запускается приём, а затем передача. Так как на инициализацию DMA уходит немного времени, первый байт может прийти битым или вообще не будет получен, если ESP ответит слишком быстро.

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +			readEspResponse(receiveBuffer);
Думаю это нужно выделить в отдельный поток. Если ESP не получит ответ за секунду, то данный поток прыгнет в начало цикла и зависнет, пока не придет новая команда. Если ESP ответит до того как новая команда прилетит, вызов readEspResponse задержится до этого момента. Поэтому лучше прием отправку распараллелить. 
Архитектура с очередью в целом хорошая.

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +		if(currentCmdRFID == buf[2]){
Может &&?

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +uint16_t uiCrc16Calc(uint8_t  *buf, uint8_t length){
Ты уверен, что buf никогда не null? Если да, то ок. Если нет, то обычно такие указатели всегда в самом начале следует проверять на null

2023-05-17 11:06 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/rfid.c
> +				if(osMessageQueueGet (rfidReceiveQueueHandle, &receiveStage, 0, 1000) == ReceiveOK)
Если вышли по таймауту, для надёжности нужно разрядить DMA

2023-05-30 05:42 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +			readEspResponse(receiveBuffer);
С таймингами можно поработать 1 секунда взята ориентировочно. Можно выставить 30 с

2023-05-30 05:49 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +uint16_t uiCrc16Calc(uint8_t  *buf, uint8_t length){
расчёт crc идёт, либо когда в очереди rfidReceiveQueueHandle появилось сообщение, либо когда мы его сами отправляем null там точно не будет

2023-05-30 08:53 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/app.c
> +extern osMessageQueueId_t espSendQueueHandle;
Как это реализовать? Кроме того, как перенести объявление очереди из main в esp.h?

2023-05-30 08:54 UTC, mrkamalov commented on Software/VelvetApp/Core/Inc/rfid.h
> +extern uint8_t currentTag[6];
+

2023-05-30 08:54 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +void sendMsgToESP(void *argument){
+

2023-05-30 08:55 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +	}
+

2023-05-30 08:55 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/main.c
> +__weak void readWeight(void *argument)
+

2023-05-30 08:55 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/main.c
> +__weak void sendMsgToESP(void *argument)
+

2023-05-30 08:55 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +uint8_t currentTag[6] = {0};
+

2023-05-30 08:55 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +}
+

2023-05-30 08:55 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +void readRfid(void *argument)
+

2023-05-30 08:56 UTC, mrkamalov commented on Software/VelvetApp/Core/Inc/adc.h
> +
Как убрать файлы и строки из pr?

2023-05-30 08:56 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +#define ReceiveOK 1
+

2023-05-30 08:57 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/uartCallback.c
> +extern osMessageQueueId_t rfidReceiveQueueHandle;
Как это реализовать? Кроме того, как перенести объявление очереди из main в esp.h/rfid?

2023-05-30 08:57 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +}
+

2023-05-30 08:57 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +uint8_t isTagsEqual(uint8_t* newTag, uint8_t* currentTag){
+

2023-05-30 08:58 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +extern UART_HandleTypeDef huart4;
+

2023-05-30 08:58 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +	for(i=1;i<7;i++) sendBuffer[i] = tagBuf[i-1];
+

2023-05-30 08:58 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +
+

2023-05-30 08:58 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/esp.c
> +		HAL_UART_Receive_DMA(&huart4,receiveBuffer,8);
+

2023-05-30 08:58 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +		if(currentCmdRFID == buf[2]){
+

2023-05-30 08:58 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/rfid.c
> +				if(osMessageQueueGet (rfidReceiveQueueHandle, &receiveStage, 0, 1000) == ReceiveOK)
+

2023-05-30 13:36 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/app.c
> +extern osMessageQueueId_t espSendQueueHandle;
Так реализовывать нельзя, получается многократное определение

2023-05-30 13:41 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/app.c
> +extern osMessageQueueId_t espSendQueueHandle;
Можно определить очередь в esp.c и в заголовочном файле указать extern

2023-05-30 13:47 UTC, mrkamalov commented on Software/VelvetApp/Core/Src/uartCallback.c
> +extern osMessageQueueId_t rfidReceiveQueueHandle;
Тоже самое что и выше

2023-05-30 15:09 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/esp.c
> +				osMessageQueuePut(espSendQueueHandle, &sendMessageType, 0, 0);
Так делать нельзя. sendMessageType у тебя глобальная переменная, а у отправителя и у приёмника должны быть локальные переменные. Иначе получается race condition

2023-05-30 16:02 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/app.c
> +extern osMessageQueueId_t espSendQueueHandle;
Согласен

2023-05-30 16:03 UTC, Kvenecusghost commented on Software/VelvetApp/Core/Src/uartCallback.c
> +extern osMessageQueueId_t rfidReceiveQueueHandle;
Согласен

2023-06-02 16:28 UTC, merged